#spring.datasource.url=jdbc:mysql://localhost:3306/books_data2?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql = true
#spring.datasource.driver-class-name =com.mysql.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books_data2?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
